// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class FAILLOGINTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void fAILLOGIN() {
    driver.Navigate().GoToUrl("https://login.yahoo.com/config/login?.src=fpctx&.intl=us&.lang=en-US&.done=https://www.yahoo.com");
    driver.Manage().Window.Size = new System.Drawing.Size(1296, 776);
    driver.FindElement(By.Id("login-username")).SendKeys("ergerg@vfvf.bg");
    driver.FindElement(By.Id("login-signin")).Click();
    driver.FindElement(By.CssSelector(".challenge")).Click();
    driver.FindElement(By.CssSelector(".login-bg-outer")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".error")).Text, Is.EqualTo("Sorry, we don\\\'t recognize this email."));
  }
}
